"use client";
import { Clipboard, Check, Search } from "lucide-react";
import { useState } from "react";
const prompts = [
  { title: "Cinematic Reel Shot", category: "Video", description: "A premium vertical shot for an AI video model.", prompt: "Create a cinematic vertical clip with a clear subject, intentional camera motion, realistic lighting, natural micro-movements and a polished commercial look. Prioritize believable physics, clean composition and stable identity." },
  { title: "Product Hero Image", category: "Product Photography", description: "Clean commercial product photography prompt.", prompt: "Create a premium studio product photograph with controlled soft lighting, subtle shadows, accurate material texture, clean negative space and a simple editorial composition." },
  { title: "Instagram Story Sequence", category: "Instagram", description: "Turn one idea into a short story arc.", prompt: "Turn the topic into a 3-part Instagram story: hook, useful insight, and clear CTA. Keep each frame short, conversational and easy to scan on mobile." },
  { title: "YouTube Research Brief", category: "YouTube", description: "Structure a video research outline before scripting.", prompt: "Build a YouTube research brief with audience problem, promise, supporting examples, counterpoints, suggested structure, title angles and a concise CTA." },
  { title: "Small Business Offer", category: "Business", description: "Clarify a service offer without hype.", prompt: "Rewrite this small-business offer around customer, problem, outcome, proof and next step. Keep the language specific, credible and free from unsupported claims." },
  { title: "Marketing Content Pillars", category: "Marketing", description: "Build a repeatable content framework.", prompt: "Create five content pillars for the niche, then provide sample topics for each pillar across education, proof, story, objection handling and conversion." },
  { title: "Portrait Image Prompt", category: "Image", description: "Editorial portrait starting point.", prompt: "Create a natural editorial portrait with realistic skin texture, coherent anatomy, subtle depth of field, intentional lighting and uncluttered background separation." }
];
const cats = ["All", "Video", "Image", "Instagram", "YouTube", "Business", "Marketing", "Product Photography"];
export function PromptLibrary() { const [q,setQ]=useState(""); const [cat,setCat]=useState("All"); const [copied,setCopied]=useState<string>(""); const list=prompts.filter(p=>(cat==="All"||p.category===cat)&&`${p.title} ${p.description} ${p.prompt}`.toLowerCase().includes(q.toLowerCase())); const copy=async(id:string,text:string)=>{await navigator.clipboard.writeText(text);setCopied(id);setTimeout(()=>setCopied(""),1600)}; return <div><div className="directory-controls"><div className="search-wrap"><Search size={18}/><input placeholder="Search prompts..." value={q} onChange={e=>setQ(e.target.value)}/></div><select value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></div><div className="prompt-grid">{list.map((p,i)=><article className="card prompt-card" key={p.title}><div className="tag">{p.category}</div><h3>{p.title}</h3><p>{p.description}</p><div className="prompt-box">{p.prompt}</div><button className="button button-secondary button-small" onClick={()=>copy(String(i),p.prompt)}>{copied===String(i)?<Check size={15}/>:<Clipboard size={15}/>} {copied===String(i)?"Copied":"Copy prompt"}</button></article>)}</div></div> }
